disabled_rules:
    - line_length
    - variable_name
    - type_name
    - force_cast
    - file_length
    - large_tuple

opt_in_rules:
#    - missing_docs # Commented until the rule is fixed. https://github.com/realm/SwiftLint/issues/728
    - vertical_whitespace

included:
    - Sources
